### PR TITLE
improved regex for imgur galleries

### PR DESCRIPTION
**Pull request by Fusselwurm**
- support `/a/` , not only `/gallery/`
- match also if `<a>` contains more attributes than just `href`
- dont be too greedy when matching link text

*edit: due to inactivity on the author's part, I decided to re-publish under `nodebb-plugin-embed-imgur-2`*

### CODE REVIEW

**Comment by TobiTenno** [comment]
this works excellently.
I know it's been a long while, @Fusselwurm, but i'd re-publish  it yourself if they don't pull it in.

**Comment by Fusselwurm** [comment]
@aliasfalse I was hoping @estebanconstante would do us the honor https://github.com/estebanconstante/nodebb-plugin-embed-imgur , but it looks like he doesnt publish publicly.

**Comment by Fusselwurm** [comment]
@aliasfalse  there we go: `npm install nodebb-plugin-embed-imgur-2` .

**Comment by moonmidas** [comment]
@Fusselwurm thanks! I've been using ns-embed instead as I can embed new ones, so I stopped using this plugin.

**Comment by TobiTenno** [comment]
@Fusselwurm i ended up installing yours from github, works fantastically.

**Comment by Fusselwurm** [comment]
(I like to keep such things open for informational purposes, but I really need to clean up my PR list :grimacing: )

**Comment by TobiTenno** [comment]
it would be nice if @a5mith would've merged it in 🤦‍♂

**Pull request closed without merging**
